export * from "./Feed";
export * from "./Feedbacks";
export * from "./Footer";
export * from "./Forms";
export * from "./Head";
export * from "./Header";
export * from "./Login";
export * from "./Photo";
export * from "./User";
